/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormPemesenan extends javax.swing.JInternalFrame {

    private Connection conn;

    String id_jadwal = "";

    /**
     * Creates new form pemesanan
     */
    public FormPemesenan() throws SQLException {
        this.conn = config.configDB();
        initComponents();
        cb_awal.removeAllItems();
        cb_tujuan.removeAllItems();
        load_table();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tb_nik = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tb_nama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tb_telepon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tb_jumlah = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cb_awal = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cb_tujuan = new javax.swing.JComboBox<>();
        bt_cek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_list = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tb_kodejadwal = new javax.swing.JTextField();
        tb_total = new javax.swing.JTextField();
        bt_pesan = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_submit = new javax.swing.JTable();
        btnAdmin = new javax.swing.JButton();
        bt_refresh = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMaximumSize(new java.awt.Dimension(920, 549));
        setMinimumSize(new java.awt.Dimension(920, 549));
        setPreferredSize(new java.awt.Dimension(920, 549));

        jPanel1.setBackground(new java.awt.Color(104, 142, 78));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pemesanan Tiket", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setMaximumSize(new java.awt.Dimension(896, 507));
        jPanel1.setMinimumSize(new java.awt.Dimension(896, 507));
        jPanel1.setPreferredSize(new java.awt.Dimension(896, 507));

        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel3.setText("Telepon");

        jLabel4.setText("Jumlah");

        jLabel5.setText("Kota Awal");

        cb_awal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_awalActionPerformed(evt);
            }
        });

        jLabel6.setText("Kota Tujuan");

        bt_cek.setBackground(new java.awt.Color(102, 255, 51));
        bt_cek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Cek.png"))); // NOI18N
        bt_cek.setText("Cek");
        bt_cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cekActionPerformed(evt);
            }
        });

        tbl_list.setBackground(new java.awt.Color(204, 204, 204));
        tbl_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Jadwal", "Maskapai", "Keberangkatan", "Kedatangan", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_list);

        jLabel7.setText("Kode Jadwal");

        jLabel8.setText("Total");

        tb_kodejadwal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tb_kodejadwal.setEnabled(false);
        tb_kodejadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_kodejadwalActionPerformed(evt);
            }
        });

        tb_total.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tb_total.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tb_kodejadwal)
                    .addComponent(tb_total, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tb_kodejadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tb_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bt_pesan.setBackground(new java.awt.Color(51, 255, 51));
        bt_pesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Submit.png"))); // NOI18N
        bt_pesan.setText("Submit");
        bt_pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_pesanActionPerformed(evt);
            }
        });

        tbl_submit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Pemesananan", "ID Jadwal", "NIK", "Nama", "Telepon", "Jumlah Tiket", "Total"
            }
        ));
        jScrollPane2.setViewportView(tbl_submit);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_cek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(53, 53, 53)
                                .addComponent(tb_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tb_nik)
                                    .addComponent(tb_nama, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_awal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(96, 96, 96)
                                .addComponent(tb_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))))
            .addComponent(bt_pesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(455, 455, 455))
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tb_nik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tb_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tb_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_awal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tb_telepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cek)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_pesan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAdmin.setBackground(new java.awt.Color(204, 204, 204));
        btnAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Admin.png"))); // NOI18N
        btnAdmin.setText("Admin");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });

        bt_refresh.setBackground(new java.awt.Color(255, 255, 102));
        bt_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Refresh.png"))); // NOI18N
        bt_refresh.setText("Refresh");
        bt_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bt_refresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdmin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmin)
                    .addComponent(bt_refresh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_awalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_awalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_awalActionPerformed

    private void bt_cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cekActionPerformed
        // TODO add your handling code here:
        if (cb_awal.getSelectedIndex() != cb_tujuan.getSelectedIndex()) {
            tb_kodejadwal.setText("");
            tb_total.setText("");
            String kota_awal_cb = cb_awal.getSelectedItem().toString();
            String kota_awal = kota_awal_cb.substring(0, 4);
            String kota_tujuan_cb = cb_tujuan.getSelectedItem().toString();
            String kota_tujuan = kota_tujuan_cb.substring(0, 4);

            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Kode Jadwal");
            model.addColumn("Maskapai");
            model.addColumn("Keberangkatan");
            model.addColumn("Kedatangan");
            model.addColumn("Harga");

            try (Connection connection = config.configDB();
                PreparedStatement stm = connection.prepareStatement(
                    "SELECT jadwal.ID_JADWAL, pesawat.MASKAPAI, jadwal.KEBERANGKATAN, jadwal.KEDATANGAN, jadwal.HARGA " +
                    "FROM jadwal, pesawat " +
                    "WHERE jadwal.ID_PESAWAT = pesawat.ID_PESAWAT " +
                    "AND jadwal.KOTA_AWAL = ? " +
                    "AND jadwal.KOTA_TUJUAN = ?",
                    ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY)) {

                stm.setString(1, kota_awal);
                stm.setString(2, kota_tujuan);

                try (ResultSet res = stm.executeQuery()) {
                    if (res.first()) {
                        model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
                        while (res.next()) {
                            model.addRow(new Object[]{res.getString(1), res.getString(2), res.getString(3), res.getString(4), res.getString(5)});
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Jadwal penerbangan tidak tersedia!");
                    }
                }
                tbl_list.setModel(model);

            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data: " + e.getMessage());
            }

        } else {
            JOptionPane.showMessageDialog(null, "Kota awal dan tujuan tidak boleh sama!");
        }
    }//GEN-LAST:event_bt_cekActionPerformed

    private void tbl_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_listMouseClicked
        // TODO add your handling code here:
        int baris = tbl_list.rowAtPoint(evt.getPoint());
        tb_kodejadwal.setText(tbl_list.getValueAt(baris, 0).toString());
        id_jadwal = tbl_list.getValueAt(baris, 0).toString();
        int total = Integer.parseInt(String.valueOf(tbl_list.getValueAt(baris, 4))) * Integer.parseInt(tb_jumlah.getText());
        tb_total.setText(String.valueOf(total));
    }//GEN-LAST:event_tbl_listMouseClicked

    private void tb_kodejadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_kodejadwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_kodejadwalActionPerformed

    private void bt_pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_pesanActionPerformed
        try {
            int jumlah = Integer.parseInt(tb_jumlah.getText());
            int total = Integer.parseInt(tb_total.getText());

            // Pastikan variabel id_jadwal sudah diinisialisasi dengan benar sebelum digunakan
            // Contoh inisialisasi: String id_jadwal = "123";

            // Pastikan ID_PEMESANAN diatur sebagai auto-increment atau berikan nilai yang unik
            String sql = "INSERT INTO pemesanan (id_jadwal, nik, nama, telpon, jumlah_tiket, total) VALUES (?,?,?,?,?,?)";
            try {
                PreparedStatement stat = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

                // Gantilah ini dengan cara yang sesuai untuk mendapatkan nilai id_jadwal
                stat.setString(1, id_jadwal);
                stat.setString(2, tb_nik.getText());
                stat.setString(3, tb_nama.getText());
                stat.setString(4, tb_telepon.getText());
                stat.setInt(5, jumlah);
                stat.setInt(6, total);

                stat.executeUpdate();

                // Dapatkan nilai yang dihasilkan (auto-incremented key) jika perlu
                int generatedId = -1; // Default value jika tidak ada ID yang dihasilkan
                try (ResultSet generatedKeys = stat.getGeneratedKeys()) {
                    if (generatedKeys.next()) {
                        generatedId = generatedKeys.getInt(1);
                        System.out.println("ID_PEMESANAN yang baru: " + generatedId);
                    }
                }

                JOptionPane.showMessageDialog(null, "DATA BERHASIL DISIMPAN");

                // Perbarui model tabel untuk menampilkan data yang baru saja disimpan
                DefaultTableModel model = (DefaultTableModel) tbl_submit.getModel();
                model.addRow(new Object[]{generatedId, id_jadwal, tb_nik.getText(), tb_nama.getText(), tb_telepon.getText(), jumlah, total});

                // Kosongkan elemen GUI atau lakukan tindakan selanjutnya sesuai kebutuhan
                // kosong();
                // txtKode.requestFocus();
                // load_table();
            } catch (SQLException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "DATA GAGAL DISIMPAN: " + e.getMessage());
            }
        } catch (NumberFormatException e) {
            // Tangkap kesalahan konversi angka
            JOptionPane.showMessageDialog(null, "Masukkan angka yang valid untuk jumlah dan total!");
        }
    }//GEN-LAST:event_bt_pesanActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        FormLogin k = null;
        try {
            k = new FormLogin();
        } catch (SQLException ex) {
            Logger.getLogger(FormMenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        k.setVisible(true);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void bt_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_refreshActionPerformed
        // TODO add your handling code here:
        cb_awal.removeAllItems();
        cb_tujuan.removeAllItems();
        load_table();
    }//GEN-LAST:event_bt_refreshActionPerformed

    private void load_table() {
        // membuat tampilan model tabel

        //menampilkan data database kedalam tabel
        try {
            String sql_kota = "SELECT * FROM kota";
            java.sql.Connection conn = (Connection) config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res;
            res = stm.executeQuery(sql_kota);
            while (res.next()) {
                cb_awal.addItem(res.getString(1) + " - " + res.getString(2));
                cb_tujuan.addItem(res.getString(1) + " - " + res.getString(2));
            }
        } catch (Exception e) {
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPemesenan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPemesenan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPemesenan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPemesenan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new FormPemesenan().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FormPemesenan.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cek;
    private javax.swing.JButton bt_pesan;
    private javax.swing.JButton bt_refresh;
    private javax.swing.JButton btnAdmin;
    private javax.swing.JComboBox<String> cb_awal;
    private javax.swing.JComboBox<String> cb_tujuan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tb_jumlah;
    private javax.swing.JTextField tb_kodejadwal;
    private javax.swing.JTextField tb_nama;
    private javax.swing.JTextField tb_nik;
    private javax.swing.JTextField tb_telepon;
    private javax.swing.JTextField tb_total;
    private javax.swing.JTable tbl_list;
    private javax.swing.JTable tbl_submit;
    // End of variables declaration//GEN-END:variables
}
